### ISSUE TITLE
QuickstartDeployARM-bicep.md

### ISSUE THREAD

**Issue by TMAHS** [microsoft/fhir-proxy#30]
On fhir-proxy/docs/QuickstartDeployARM-bicep.md

Prerequisites for Step 1 Deployment on bullet items under "access to the following fhir server parameters..." can you clarify or point to the specific fhir server client in reference for the server.  It is assumed to be a confidential client app registration, but that is not clear.

Step 2 CLI:  #12  Can you confirm the path.  Found in the \scripts directory not the \templates

Step 3 Item #47.  It would be helpful to have a bit more clarification.  The screen shot shows "Allow unauthenticated access" as well as the CLI info.  If someone elects to use require authentication can you point to additional guidance?

Step 3 Item #47.  After clicking the permissions button, is this a possible output?  "Permissions are only allowed to be selected on a newly created Azure Active Directory application."

This is a quickstart deployment doc, but it would be nice to have some additional guidance in "After the install" other can verification of Key vault values.  Perhaps a suggestion of next step(s).

**Comment by erikhoward** [comment]
Closing. Merged PR.
