### ISSUE TITLE
deployfhirproxy.bash fails due to typo

### ISSUE THREAD

**Issue by mkoivi-ms** [microsoft/fhir-proxy#46]
Running script returns error - in following line 'resource-group' is misspelled.

	echo "Creating Function App MSI for KeyVault Access..."
	msi=$(az functionapp identity assign --subscription $subscriptionId **--resouce-group** $resourceGroupName --name $proxyAppName --query "principalId" --out tsv)

**Comment by v-pbartley** [comment]
PR https://github.com/microsoft/fhir-proxy/pull/47 - resolved issue
