### ISSUE TITLE
command suggested in createproxyserviceclient.bash fails when running it

### ISSUE THREAD

**Issue by imrago-medxnote** [microsoft/fhir-proxy#50]
When running the createproxyserviceclient.bash I got this warning:

WARNING: Invoking "az ad app permission grant --id xxxxx --api yyyy" is needed to make the change effective

when I execute that, I am getting the following error:

"Insufficient privileges to complete the operation."

Running it as an admin. What needs to be changed?

**Comment by daemel** [comment]
Please ensure you have the RBAC role of Application Administrator.  We recommend in the Readme that customers apply the permission via the portal, to know if you have everything installed correctly the following values should be set in your keyvault 

Keyvault values loaded by this script 

Name                             
--------------------------------
FP-SC-TENANT-NAME               
FP-SC-CLIENT-ID               
FP-SC-SECRET                   
FP-SC-RESOURCE         
FP-SC-URL                   

As longs as those values are set, you can apply the permissions you need via these instructions https://github.com/microsoft/fhir-proxy/tree/main/scripts#step-3--grant-admin-access-portal

**Comment by imrago-medxnote** [comment]
Thank you for the explanation, I was able to apply the permissions using the portal
