### ISSUE TITLE
Maturity of this project and possible support?

### ISSUE THREAD

**Issue by dustinmoris** [microsoft/fhir-proxy#55]
Hi, I am currently working on a project where I am seriously considering the use of the Azure FHIR Service from the managed Health APIs but we need to support multi-tenancy and other auth scenarios and this project looks like it could be a good fit.

My question is really if this project is mature enough that Microsoft would recommend using it in production? Also if we were to deploy this to our production environment what options of support do we have if we run into issues? I understand that this is an open source project but given that this is centred around security and authentication which is a domain that is notoriously hard to get right and very easy to mess up I am wondering how realistic it would be to maintain this ourselves if we did run into some problems and if Microsoft can provide any guidance/guarantees around it?

Also is there any other managed (PaaS) offering in Azure at the moment which we could leverage to provide multi-tenancy around the Azure FHIR Server or is this proxy our best bet?

Many thanks!

**Comment by sordahl-ga** [comment]
Closing this issue due to age, please reference the 2.0 branch of this repo since it has superior functionality and enhancements. It is also actively maintained.
