### ISSUE TITLE
Unable to make a Postman request to the FHIR Proxy URL

### ISSUE THREAD

**Issue by rohitp934** [microsoft/fhir-proxy#56]
I have set up the FHIR Proxy according to the steps in this documentation: https://github.com/microsoft/fhir-proxy/tree/main/scripts#setup

I have added the Resource Reader and Writer permissions as well to the Service Principal and granted Admin Consent.

Used the Postman Environment that was generated and the Sample Postman Commands Collection to test the FHIR Proxy Endpoint.
I have retrieved access token with the following URL: https://login.microsoftonline.com/{{tenantId}}/oauth2/token
The GET Metadata request works, but unfortunately, when I try to GET patients, I am getting the following:
```
{
    "resourceType": "OperationOutcome",
    "id": "fb80820854f0254db3a4c725890b3ddd",
    "meta": {
        "lastUpdated": "2022-05-13T04:43:41.4825864+00:00"
    },
    "issue": [
        {
            "severity": "error",
            "code": "forbidden",
            "diagnostics": "Authorization failed."
        }
    ]
}
```
Is there a specific step that I am missing?

**Comment by daemel** [comment]
it looks like the permissions grant did not work as it should - can you check the portal, it should look like the example in Step 3 - https://github.com/microsoft/fhir-proxy/tree/main/scripts#step-3--grant-admin-access-portal.  If that does not help, then can you share the URL you are using (you can remove the tenant ID and server name).

**Comment by rohitp934** [comment]
Okay here are the permissions granted as per Step 3
![fhirproxy](https://user-images.githubusercontent.com/54208873/168784346-39ac64db-c825-41a3-b2c4-b98e4b882bdf.PNG)

The Authorization request and List Patients request are from this sample collection: https://github.com/microsoft/fhir-proxy/blob/main/samples/FHIR_Commands.postman_collection.json

**Comment by JakeGinnivan** [comment]
FWIW, I hit the same issue after doing setup steps end to end on a new deployment, the setup worked a few months ago.

**Comment by sordahl-ga** [comment]
Closed to v2 version
