### ISSUE TITLE
deployfhirproxy.bash not working with CLI 2.37.0

### ISSUE THREAD

**Issue by LuisARB** [microsoft/fhir-proxy#58]
this line

stepresult=$(az ad app update --id $spappid --reply-urls $spreplyurls)

or this one in v2.0

stepresult=$(az ad app update --id $spappid --reply-urls $spreplyurls --identifier-uris "api://"$functionAppHost)

is not working with last version of Azure CLI due --reply-urls is no longer a valid parameter

**Comment by sordahl-ga** [comment]
This issue should now be resolved in the v2.0 branch and is validated against azure CLI 2.42+  the v2.0 branch is actively maintained the main branch is not....
