### ISSUE TITLE
deploy proxy script does not always add app roles and can result in a 401

### ISSUE THREAD

**Issue by daemel** [microsoft/fhir-proxy#6]
URL to file scripts/deployfhirproxy.bash

**Comment by venkateshtarra** [comment]
Hi Daemel,

Is there any update on this issue as I am getting 401 error while trying to access proxy API from postman.

Thanks in advance.

**Comment by mikaelweave** [comment]
@venkateshtarra - until the pull request get merged, you can work around this issue by executing the script from the `scripts` folder.

Do this:
```bash
cd scripts
bash deployfhirproxy.bash
```

Not this:
```bash
bash scripts/deployfhirproxy.bash
```
