### ISSUE TITLE
Cannot perform write operation on patient resource using postman with fhir proxy.

### ISSUE THREAD

**Issue by Kedar782** [microsoft/fhir-proxy#66]
Hello team,

I have added fhir proxy using the v2 branch. I used AAD as an identity provider also MSI as an authentication method.
I followed this documentation to create a smart client. https://github.com/microsoft/fhir-proxy/tree/v2.0/scripts

After creating the smart client, I can get the access token using authorization code flow, and also I can get the patient resource. (Get request is working for patient resource).
When I make a post request I'm getting a 401 error stating that Must have to Create/Write Permissions on resource type Patient.

Anybody here has any idea what I'm doing wrong here?

smart client name:- proxy10391-smart-client-2
fhir proxy:- sfp-proxy10391.azurewebsites.net
fhir server:-fhirstandalonecli
I'm adding some screenshots.

IAM blade for my fhir server:-(ADDING FHIR CONTRIBUTOR ROLE FOR MY FHIR PROXY)
![image](https://user-images.githubusercontent.com/87669844/193346734-4e7f5984-b4cb-468f-b247-1520a6efa869.png)

API Permissions for fhir proxy:-

![image](https://user-images.githubusercontent.com/87669844/193346916-02f7bdfc-2fa6-4a5c-887f-772edda34e44.png)

App Roles for fhir proxy:-
![image](https://user-images.githubusercontent.com/87669844/193346994-fac6964d-9bbe-44fc-92f2-256683eed62b.png)

Scopes for fhir proxy:-
![image](https://user-images.githubusercontent.com/87669844/193347081-f34df5cc-32dc-4027-aaf6-8ed452e13346.png)

API Permissions for smartclient:-
![image](https://user-images.githubusercontent.com/87669844/193347375-8f84c32f-2b38-4945-80c0-80504fb7f576.png)

Scopes and App roles are empty for smartclient.

Postman Operations:-
Getting access token:-
![image](https://user-images.githubusercontent.com/87669844/193347736-22dc1d81-a1c0-4d92-ac85-398244f51315.png)
Get Patient Resource using the access token above:-
![image](https://user-images.githubusercontent.com/87669844/193347875-d29ffc1d-df95-4df7-914f-e1112db08427.png)
Error for post request:-
Header:-
![image](https://user-images.githubusercontent.com/87669844/193348001-e56b750f-8850-41c2-bdfd-6e5f752c7a73.png)
Body:-
![image](https://user-images.githubusercontent.com/87669844/193348070-8260a550-48b2-43fe-8dba-4d29d2104b67.png)
Authorization:-
![image](https://user-images.githubusercontent.com/87669844/193348244-1a3484e8-aa49-4410-a762-c541b3f0a806.png)

I will really appreciate your help. Thanks in advance!

**Comment by sordahl-ga** [comment]
Can you share the scopes granted in your access token.

**Comment by Kedar782** [comment]
Solved with deleting the old proxy and deploying the new one.
