### ISSUE TITLE
Limited access to FHIR resource.

### ISSUE THREAD

**Issue by Kedar782** [microsoft/fhir-proxy#67]
Hello team,

I basically got standalone launch working using this (https://github.com/microsoft/fhir-proxy/tree/v2.0/scripts).
I'm using AAD as an identity provider and MSI as the authentication method.
I want to pass the g(10) certification for ONC. I have given added permissions for every fhir resource.
For the limited access launch app, I need to give access to only some resources for the same client.
Any idea how can I achieve it? Seems like I can accept/deny all. I cannot select an individual.
I want to achieve something like this for my permissions for the smart client I have created.
![image](https://user-images.githubusercontent.com/87669844/193433710-8f851a12-ccc4-4541-bb52-fd4b67800e9c.png)

I will really appreciate your help guys!

**Comment by sordahl-ga** [comment]
This should be addressed with the dynamic session scopes enhancement merged into the v2.0 branch, please re-clone the repo and see the following documentation:
https://github.com/microsoft/fhir-proxy/blob/v2.0/docs/ConfigureProxyONCg10.md
