### ISSUE TITLE
SMART on FHIR - Well-known configuration missing : launch-ehr, context-banner, context-style, context-ehr-patient, permission-user

### ISSUE THREAD

**Issue by rodriguezrm** [microsoft/fhir-proxy#73]
While testing with Inferno tool (g)(10) section "3 EHR Practitioner App" I'm getting an error

Steps from 3.1.01  to 3.1.04 are ok

Step 3.1.05 error

3.1.05 Well-known configuration declares support for required capabilities
The following capabilities required for this scenario are missing: launch-ehr, context-banner, context-style, context-ehr-patient, permission-user

A SMART on FHIR server SHALL convey its capabilities to app developers by listing the SMART core capabilities supported by their implementation within the Well-known configuration file. This test ensures that the capabilities required by this scenario are properly documented in the Well-known file.

well_known_configuration

{"token_endpoint":"https://sfp-xxx.azurewebsites.net/oauth2/token","token_endpoint_auth_methods_supported":["client_secret_post","private_key_jwt","client_secret_basic"],"jwks_uri":"https://login.microsoftonline.com/c5a06aa4-xxx-4e46-86ac-b81d53d73ee6/discovery/v2.0/keys","response_modes_supported":["query","fragment","form_post"],"subject_types_supported":["pairwise"],"id_token_signing_alg_values_supported":["RS256"],"response_types_supported":["code","id_token","code id_token","id_token token"],"scopes_supported":["openid","profile","email","offline_access"],"issuer":"https://login.microsoftonline.com/c5a06aa4-xxx-4e46-86ac-b81d53d73ee6/v2.0","request_uri_parameter_supported":false,"userinfo_endpoint":"https://graph.microsoft.com/oidc/userinfo","authorization_endpoint":"https://sfp-xxx.azurewebsites.net/oauth2/authorize","device_authorization_endpoint":"https://login.microsoftonline.com/c5a06aa4-xxx-4e46-86ac-b81d53d73ee6/oauth2/v2.0/devicecode","http_logout_supported":true,"frontchannel_logout_supported":true,"end_session_endpoint":"https://login.microsoftonline.com/c5a06aa4-xxx-4e46-86ac-b81d53d73ee6/oauth2/v2.0/logout","claims_supported":["sub","iss","cloud_instance_name","cloud_instance_host_name","cloud_graph_host_name","msgraph_host","aud","exp","iat","auth_time","acr","nonce","preferred_username","name","tid","ver","at_hash","c_hash","email"],"kerberos_endpoint":"https://login.microsoftonline.com/c5a06aa4-xxx-4e46-86ac-b81d53d73ee6/kerberos","tenant_region_scope":"NA","cloud_instance_name":"microsoftonline.com","cloud_graph_host_name":"graph.windows.net","msgraph_host":"graph.microsoft.com","rbac_url":"https://pas.windows.net","capabilities":["launch-standalone","client-public","Patient Access for Standalone Apps","sso-openid-connect","context-standalone-patient","permission-offline","permission-patient","client-confidential-symmetric"]}

To reproduce the error

Run test # 3 on https://inferno.healthit.gov/suites/test_sessions/3294991d-8299-4ea0-86ad-b8d5b1e87af6

Provide your Fhir Proxy Url, client and secret

Use this link to complete test https://inferno.healthit.gov/suites/custom/smart/launch?launch=123&iss=https://sfp-proxyxxx.azurewebsites.net/fhir

 
![2022-11-16_11-52-20](https://user-images.githubusercontent.com/47366596/202213766-772e8850-34b8-4f45-8b3d-91d96facdbb8.png)

**Comment by sordahl-ga** [comment]
This has been resolved with various v2.0 merges please re-clone
Please see the ONC documentation for fhir-proxy here:
https://github.com/microsoft/fhir-proxy/blob/v2.0/docs/ConfigureProxyONCg10.md
