### ISSUE TITLE
AADSTS9002327: Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requestsIssue

### ISSUE THREAD

**Issue by vohuythao** [microsoft/fhir-proxy#76]
**Describe the Issue **

When using FHIR Proxy and authentication with Azure AD,

Got this error in the SMARTProxyToken function

![image](https://user-images.githubusercontent.com/14121587/202886306-ef67aa90-c5d5-4cb8-b19f-d0624dd5360c.png)

During OAuth 2.0 “authorization code with PKCE” grant, Azure AD requires Origin header to be present on the request to /token endpoint. If header is not present, authorization flow fails with the following error:

Error: AADSTS9002327: Tokens issued for the ‘Single-Page Application’
client-type may only be redeemed via cross-origin requests

Unfortunately, we cannot adding this header to the flow, hence the request for a token fails.

Is there a way to add a custom header into the requests that are executed behind ?

Thank you

**Comment by sordahl-ga** [comment]
Can you detail your auth request.  I don't see this in my public client registration.  Did you create your client with the -u switch in the createproxysmartclient script?

**Comment by vohuythao** [comment]
Hello @sordahl-ga 

Thank you for your comment, I created the smartclient with this document

https://github.com/microsoft/fhir-proxy/blob/v2.0/docs/ConfigureProxyONCg10.md

The command is
./createproxysmartclient.bash -k <key vault name> -n oncprivate -p -a

So it means I don't use -u switch

**Comment by vohuythao** [comment]
Here is the detail of auth request in Inferno

![image](https://user-images.githubusercontent.com/14121587/203215465-5be2c8a3-6ab5-4ae8-a11c-26bf52da7351.png)

Thank you

**Comment by vohuythao** [comment]
This is solved by deleted everything and follow this document
https://github.com/microsoft/fhir-proxy/blob/v2.0/docs/ConfigureProxyONCg10.md
