### ISSUE TITLE
Getting error for bulk data. Inferno Test 7.3.03. Getting Error with status 500 for NDJSON file.

### ISSUE THREAD

**Issue by Kedar782** [microsoft/fhir-proxy#79]
I have inserted the Patient resource that conforms to the US Core Patient Profile. I'm getting an error for inferno which is not very clear.
I'm getting an error for point 7.3.03.
I'm following this document for ONC g(10) certification https://github.com/microsoft/fhir-proxy/blob/v2.0/docs/ConfigureProxyONCg10.md.
I have followed every step for test 7 (Multi Patient API) from the above document.

For enabling export on the FHIRSERVER I have performed following steps:-

1. Enabled Managed Identity on Azure API for FHIR.
2. Created an Azure storage account in the same resource of FHIRSERVER and assigned permissions to Azure API for FHIR to the storage account.
3. Selected the storage account in Azure API for FHIR as export storage account.

I have followed it from this document:- https://learn.microsoft.com/en-us/azure/healthcare-apis/azure-api-for-fhir/configure-export-data

Do I have to perform any other operations on the FHIR Server? Like in the networking tab of my storage account I have selected Enable from all networks. Do I have to select Enabled from selected virtual networks and IP addresses?

When I try to access NDJSON file for FHIR resources I get the status 500.
Please guide me with this. I have spent a long time on it and my deadline for ONC certification is very near.
 
![image](https://user-images.githubusercontent.com/87669844/203648470-843241c5-a02a-43df-8ce3-297c6e546ab0.png)

![image](https://user-images.githubusercontent.com/87669844/203648389-618bb797-2a98-482c-bce5-a5fc26370118.png)

THIS IS THE INPUT AND VALUE FOR THE REQUEST:- 

status_output:- 

[{"type":"AllergyIntolerance","url":"https://sfp-proxy23209.azurewebsites.net/fhir/_exportFile/6046bf68-ddbb-47a4-b60c-9727e792879e/20221123T202715-a5aa47db-b2ae-4567-bedf-a2716d094573/AllergyIntolerance-1.ndjson","count":2},{"type":"Group","url":"https://sfp-proxy23209.azurewebsites.net/fhir/_exportFile/6046bf68-ddbb-47a4-b60c-9727e792879e/20221123T202715-a5aa47db-b2ae-4567-bedf-a2716d094573/Group-1.ndjson","count":2},{"type":"Patient","url":"https://sfp-proxy23209.azurewebsites.net/fhir/_exportFile/6046bf68-ddbb-47a4-b60c-9727e792879e/20221123T202715-a5aa47db-b2ae-4567-bedf-a2716d094573/Patient-1.ndjson","count":2},{"type":"Provenance","url":"https://sfp-proxy23209.azurewebsites.net/fhir/_exportFile/6046bf68-ddbb-47a4-b60c-9727e792879e/20221123T202715-a5aa47db-b2ae-4567-bedf-a2716d094573/Provenance-1.ndjson","count":1}]

requires_access_token

true

bearer_token

eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJvaWQiOiI2MDQ2YmY2OC1kZGJiLTQ3YTQtYjYwYy05NzI3ZTc5Mjg3OWUiLCJ0aWQiOiI2MDQ2YmY2OC1kZGJiLTQ3YTQtYjYwYy05NzI3ZTc5Mjg3OWUiLCJzZXJ2aWNlQ2xpZW50Ijoic3lzdGVtIiwic2NwIjoic3lzdGVtLioucmVhZCBzeXN0ZW0uX29wZXJhdGlvbnMuKiIsImlzcyI6Imh0dHBzOi8vZmhpci1wcm94eS5henVyZWhlYWx0aGNhcmVhcGlzLmNvbSIsImF1ZCI6Imh0dHBzOi8vc2ZwLXByb3h5MjMyMDkuYXp1cmV3ZWJzaXRlcy5uZXQvb2F1dGgyL3Rva2VuIiwic3ViIjoiNjA0NmJmNjgtZGRiYi00N2E0LWI2MGMtOTcyN2U3OTI4NzllIiwibmJmIjoxNjY5MjM1MjMzLCJleHAiOjE2NjkyMzg4MzIsImlhdCI6MTY2OTIzNTIzM30.b6hXwQVdonn5jgZuCgH7BCQScYzbyxoS4zaUnxR16OFStjb5vun2Qnr80sdzoCFb

bulk_download_url

https://sfp-proxy23209.azurewebsites.net/fhir/_exportFile/6046bf68-ddbb-47a4-b60c-9727e792879e/20221123T202715-a5aa47db-b2ae-4567-bedf-a2716d094573/AllergyIntolerance-1.ndjson

lines_to_validate

bulk_patient_ids_in_group

26b8f4f5-441f-481e-b50a-0cd265df4f08, 6b0ad32c-eb5d-4db1-81bc-000369b9a1f5

bulk_device_types_in_group

I have no idea how to debug this. Do you have any insights on this? I will really appreciate your help.

**Comment by sordahl-ga** [comment]
This is more than likely due to invalid entities in the Group resource, make sure the Patient resources have actual local Patient reference in the resource and not urn:uuid: references. 
...
 "member": [
        {
            "entity": {
                "reference": "Patient/e91975f5-9445-c11f-cabf-c3c6dae161f2"
            }
        },
        {
            "entity": {
                "reference": "Patient/d831ec91-c7a3-4a61-9312-7ff0c4a32134"
            }
        }
    ]
...

**Comment by Kedar782** [comment]
@sordahl-ga 

Group resource has valid patient references. Please see the group and patient resources.
Group Resource:-
{
    "resourceType": "Bundle",
    "id": "e57a5900991d9a7314c569dae3ffc525",
    "meta": {
        "lastUpdated": "2022-11-28T21:39:29.9845404+00:00"
    },
    "type": "searchset",
    "link": [
        {
            "relation": "self",
            "url": "https://azure-fhir-modified.azurehealthcareapis.com/Group"
        }
    ],
    "entry": [
        {
            "fullUrl": "https://azure-fhir-modified.azurehealthcareapis.com/Group/abc08f6d-e822-4c80-8237-b52c2e7f515b",
            "resource": {
                "resourceType": "Group",
                "id": "abc08f6d-e822-4c80-8237-b52c2e7f515b",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2022-11-23T17:00:39.138+00:00"
                },
                "type": "person",
                "actual": true,
                "member": [
                    {
                        "entity": {
                            "reference": "Patient/26b8f4f5-441f-481e-b50a-0cd265df4f08"
                        },
                        "period": {
                            "start": "2014-10-08"
                        }
                    },
                    {
                        "entity": {
                            "reference": "Patient/6b0ad32c-eb5d-4db1-81bc-000369b9a1f5"
                        },
                        "period": {
                            "start": "2015-04-02"
                        }
                    }
                ]
            },
            "search": {
                "mode": "match"
            }
        }
    ]
}
Patient Resources:-
{
    "resourceType": "Bundle",
    "id": "dafa84557f2a5fd3b51fc4e7e4c6412a",
    "meta": {
        "lastUpdated": "2022-11-28T21:36:22.8386386+00:00"
    },
    "type": "searchset",
    "link": [
        {
            "relation": "self",
            "url": "https://azure-fhir-modified.azurehealthcareapis.com/Patient"
        }
    ],
    "entry": [
        {
            "fullUrl": "https://azure-fhir-modified.azurehealthcareapis.com/Patient/26b8f4f5-441f-481e-b50a-0cd265df4f08",
            "resource": {
                "resourceType": "Patient",
                "id": "26b8f4f5-441f-481e-b50a-0cd265df4f08",
                "meta": {
                    "versionId": "10",
                    "lastUpdated": "2022-11-25T01:13:47.527+00:00",
                    "source": "#AsIWLaUTqdaQcJ09",
                    "profile": [
                        "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
                    ]
                },
                "text": {
                    "status": "generated",
                    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by <a href=\"https://github.com/synthetichealth/synthea\">Synthea</a>.Version identifier: v2.6.1-3-g50f4f58f\n .   Person seed: -7901283747506674198  Population seed: 3</div>"
                },
                "extension": [
                    {
                        "extension": [
                            {
                                "url": "ombCategory",
                                "valueCoding": {
                                    "system": "http://terminology.hl7.org/CodeSystem/v3-NullFlavor",
                                    "code": "UNK",
                                    "display": "unknown"
                                }
                            },
                            {
                                "url": "text",
                                "valueString": "unknown"
                            }
                        ],
                        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race"
                    },
                    {
                        "extension": [
                            {
                                "url": "ombCategory",
                                "valueCoding": {
                                    "system": "http://terminology.hl7.org/CodeSystem/v3-NullFlavor",
                                    "code": "UNK",
                                    "display": "unknown"
                                }
                            },
                            {
                                "url": "text",
                                "valueString": "unknown"
                            }
                        ],
                        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity"
                    },
                    {
                        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
                        "valueCode": "M"
                    }
                ],
                "identifier": [
                    {
                        "system": "https://github.com/synthetichealth/synthea",
                        "value": "d831ec91-c7a3-4a61-9312-7ff0c4a32134"
                    },
                    {
                        "type": {
                            "coding": [
                                {
                                    "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                                    "code": "MR",
                                    "display": "Medical Record Number"
                                }
                            ],
                            "text": "Medical Record Number"
                        },
                        "system": "http://hospital.smarthealthit.org",
                        "value": "d831ec91-c7a3-4a61-9312-7ff0c4a32134"
                    },
                    {
                        "type": {
                            "coding": [
                                {
                                    "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                                    "code": "DL",
                                    "display": "Driver's License number"
                                }
                            ],
                            "text": "Driver's License number"
                        },
                        "system": "urn:oid:2.16.840.1.113883.4.3.25",
                        "value": "S99921496"
                    }
                ],
                "name": [
                    {
                        "use": "official",
                        "family": "Bosco882",
                        "given": [
                            "Lucien408"
                        ],
                        "prefix": [
                            "Mr."
                        ],
                        "suffix": [
                            "PharmD"
                        ]
                    }
                ],
                "telecom": [
                    {
                        "system": "phone",
                        "value": "555-510-6254",
                        "use": "home"
                    }
                ],
                "gender": "male",
                "birthDate": "1940-03-29",
                "deceasedDateTime": "1977-07-14T08:17:45+00:00",
                "address": [
                    {
                        "extension": [
                            {
                                "extension": [
                                    {
                                        "url": "latitude",
                                        "valueDecimal": 42.674176102041564
                                    },
                                    {
                                        "url": "longitude",
                                        "valueDecimal": -71.31980043648745
                                    }
                                ],
                                "url": "http://hl7.org/fhir/StructureDefinition/geolocation"
                            }
                        ],
                        "line": [
                            "934 Olson Highlands"
                        ],
                        "city": "Lowell",
                        "state": "MA",
                        "postalCode": "01854",
                        "country": "US",
                        "period": {
                            "start": "1940-03-29"
                        }
                    }
                ],
                "maritalStatus": {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
                            "code": "M",
                            "display": "Married"
                        }
                    ],
                    "text": "Married"
                },
                "multipleBirthBoolean": false,
                "communication": [
                    {
                        "language": {
                            "coding": [
                                {
                                    "system": "urn:ietf:bcp:47",
                                    "code": "en-US",
                                    "display": "English (United States)"
                                }
                            ],
                            "text": "English (United States)"
                        }
                    }
                ]
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://azure-fhir-modified.azurehealthcareapis.com/Patient/6b0ad32c-eb5d-4db1-81bc-000369b9a1f5",
            "resource": {
                "resourceType": "Patient",
                "id": "6b0ad32c-eb5d-4db1-81bc-000369b9a1f5",
                "meta": {
                    "versionId": "5",
                    "lastUpdated": "2022-11-25T01:21:08.56+00:00",
                    "source": "#AsIWLaUTqdaQcJ09",
                    "profile": [
                        "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
                    ]
                },
                "text": {
                    "status": "generated",
                    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by <a href=\"https://github.com/synthetichealth/synthea\">Synthea</a>.Version identifier: v2.6.1-3-g50f4f58f\n .   Person seed: 4286870567281389426  Population seed: 3</div>"
                },
                "extension": [
                    {
                        "extension": [
                            {
                                "url": "ombCategory",
                                "valueCoding": {
                                    "system": "http://terminology.hl7.org/CodeSystem/v3-NullFlavor",
                                    "code": "UNK",
                                    "display": "unknown"
                                }
                            },
                            {
                                "url": "text",
                                "valueString": "unknown"
                            }
                        ],
                        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race"
                    },
                    {
                        "extension": [
                            {
                                "url": "ombCategory",
                                "valueCoding": {
                                    "system": "http://terminology.hl7.org/CodeSystem/v3-NullFlavor",
                                    "code": "UNK",
                                    "display": "unknown"
                                }
                            },
                            {
                                "url": "text",
                                "valueString": "unknown"
                            }
                        ],
                        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity"
                    },
                    {
                        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
                        "valueCode": "M"
                    }
                ],
                "identifier": [
                    {
                        "system": "https://github.com/synthetichealth/synthea",
                        "value": "e91975f5-9445-c11f-cabf-c3c6dae161f2"
                    },
                    {
                        "type": {
                            "coding": [
                                {
                                    "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                                    "code": "MR",
                                    "display": "Medical Record Number"
                                }
                            ],
                            "text": "Medical Record Number"
                        },
                        "system": "http://hospital.smarthealthit.org",
                        "value": "e91975f5-9445-c11f-cabf-c3c6dae161f2"
                    },
                    {
                        "type": {
                            "coding": [
                                {
                                    "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                                    "code": "DL",
                                    "display": "Driver's license number"
                                }
                            ],
                            "text": "Driver's license number"
                        },
                        "system": "urn:oid:2.16.840.1.113883.4.3.25",
                        "value": "S99940283"
                    }
                ],
                "name": [
                    {
                        "use": "official",
                        "family": "Ritchie586",
                        "given": [
                            "Dustin31"
                        ],
                        "prefix": [
                            "Mr."
                        ]
                    },
                    {
                        "use": "old",
                        "family": "Ritchie586",
                        "given": [
                            "John43"
                        ],
                        "prefix": [
                            "Mr."
                        ],
                        "period": {
                            "start": "1940-09-05",
                            "end": "1962-04-30"
                        }
                    }
                ],
                "telecom": [
                    {
                        "system": "phone",
                        "value": "555-770-2787",
                        "use": "home"
                    }
                ],
                "gender": "male",
                "birthDate": "1940-09-05",
                "address": [
                    {
                        "extension": [
                            {
                                "extension": [
                                    {
                                        "url": "latitude",
                                        "valueDecimal": 42.1343534042923
                                    },
                                    {
                                        "url": "longitude",
                                        "valueDecimal": -72.67217549422628
                                    }
                                ],
                                "url": "http://hl7.org/fhir/StructureDefinition/geolocation"
                            }
                        ],
                        "line": [
                            "599 Schowalter Promenade"
                        ],
                        "city": "West Springfield",
                        "state": "MA",
                        "postalCode": "01089",
                        "country": "US",
                        "period": {
                            "start": "1940-09-05"
                        }
                    }
                ],
                "maritalStatus": {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
                            "code": "M",
                            "display": "Married"
                        }
                    ],
                    "text": "Married"
                },
                "multipleBirthBoolean": false,
                "communication": [
                    {
                        "language": {
                            "coding": [
                                {
                                    "system": "urn:ietf:bcp:47",
                                    "code": "en-US",
                                    "display": "English (United States)"
                                }
                            ],
                            "text": "English (United States)"
                        }
                    }
                ]
            },
            "search": {
                "mode": "match"
            }
        }
    ]
}

**Comment by vohuythao** [comment]
Hello @Kedar782 

Maybe this is the same issue with you, I met this for 7.2.05
https://github.com/microsoft/fhir-proxy/issues/83

**Comment by sordahl-ga** [comment]
There was a configuration step omitted in the documentation which is in this commit:
https://github.com/microsoft/fhir-proxy/commit/d2fc705d8701168a7de215071ab23fadd240dd0c
Please execute the missing step to set the FP-EXPORT-STORAGEACCT this should resolve the 500 error.

**Comment by Kedar782** [comment]
@sordahl-ga 

I have executed this step but I'm still getting the 500 error.
My FHIR Server and export storage account are in the same resource group.
FHIR Proxy is in a different resource group. Is that the reason why it is not working?
I'm getting 500 error for every resource in Multi Patient API test.

**Comment by Kedar782** [comment]
@sordahl-ga 
I was missing quotes for the connection string in the following command.
az functionapp config appsettings set --name <fhir-proxy-appname>  --resource-group <fhir-proxy-resource-group> --settings FP-EXPORT-STORAGEACCT=<your fhir server export storage account connection string from above>

500 errors resolved.
Thank you very much steve.
