### ISSUE TITLE
Could not find Patient Reference Patient/e91975f5-9445-c11f-cabf-c3c6dae161f2 in reference fields patient of resource Provenance/85807868-f29c-1ca9-1d2a-91665d2c4f05

### ISSUE THREAD

**Issue by vohuythao** [microsoft/fhir-proxy#80]
Hello,

When I run the Single Patient API test, I met this problem

![image](https://user-images.githubusercontent.com/14121587/204098406-16ffbd80-e769-4bbd-8376-1f4d3e3d0cc8.png)

Go to more details

"fullUrl": "https://sfp-proxy23604.azurewebsites.net/fhir/Provenance/85807868-f29c-1ca9-1d2a-91665d2c4f05", "resource": { "resourceType": "OperationOutcome", "id": "3072650f-7d47-4426-ae20-e7ff1264c31d", "issue": [ { "severity": "warning", "code": "forbidden", "diagnostics": "Could not find Patient Reference Patient/e91975f5-9445-c11f-cabf-c3c6dae161f2 in reference fields patient of resource Provenance/85807868-f29c-1ca9-1d2a-91665d2c4f05" } ] },

Then I search in FHIR data for Provenance ID and saw it also has reference to this Patient ID

![image](https://user-images.githubusercontent.com/14121587/204098439-298dd93c-12de-465c-afb0-93f9d4ed95f0.png)

I think all the correct data is there in FHIR, just don't know why Inferno throw error.

If you guys can suggest any hint, any keyword or any direction to troubleshoot, I am appreciate your help

Thank you

**Comment by sordahl-ga** [comment]
This item should be resolved with commits:
https://github.com/microsoft/fhir-proxy/commit/f0e360fa051c66b9dd34821a8ea2b3b3492e9a8d
https://github.com/microsoft/fhir-proxy/commit/efe9bf9c2bac27348b163e296923f6c0d216955b
https://github.com/microsoft/fhir-proxy/commit/bb757ca31039365b62074d777492342429178737

**Comment by vohuythao** [comment]
Yes for Patient, this is solved
Thank you
