### ISSUE TITLE
Issue"The requested \"export\" operation is not enabled"

### ISSUE THREAD

**Issue by vohuythao** [microsoft/fhir-proxy#81]
Hello team,

Currently I met this when running Inferno G10 test, Test case 7.2.04, follow this document
https://github.com/microsoft/fhir-proxy/blob/v2.0/docs/ConfigureProxyONCg10.md

![image](https://user-images.githubusercontent.com/14121587/204256627-c8a67d71-bead-4c8f-82f2-f738f4ecafa3.png)

I already turn on in the FHIR proxy
FHIRProxy.preprocessors.ONCExportPreProcess
FHIRProxy.postprocessors.ONCExportPostProcess

I go to the proxy function app and check log

Look like the export pre process and post process is already running

![image](https://user-images.githubusercontent.com/14121587/204257092-a7f930a1-57b6-4133-b539-a8b3494cdd10.png)

But it said ""The requested \"export\" operation is not enabled"

Not sure why

Do we need to enable the $export configuration in Azure API for FHIR itself
https://learn.microsoft.com/en-us/azure/healthcare-apis/fhir/configure-export-data

Thank you

**Comment by sordahl-ga** [comment]
Documentation has been updated you need to follow the instructions for enabling FHIR Export on the FHIR Service
This item should be resolved with commits:
https://github.com/microsoft/fhir-proxy/commit/bb757ca31039365b62074d777492342429178737

**Comment by vohuythao** [comment]
Thank you @Kedar782 and @sordahl-ga 

I can pass the 7.2.04 following the document.
