### ISSUE TITLE
Cannot able to rotate the FP-ACCESS-TOKEN-SECRET from proxy keyvault. Test 9.3 g(10) certification

### ISSUE THREAD

**Issue by Kedar782** [microsoft/fhir-proxy#85]
I'm following the documentation https://github.com/microsoft/fhir-proxy/blob/v2.0/docs/ConfigureProxyONCg10.md
For step 9.3, 
![image](https://user-images.githubusercontent.com/87669844/204806285-a529c98e-29eb-4b0d-b1ac-d11b9af61923.png)

I need to rotate the FP-ACCESS-TOKEN-SECRET from the key-vault of the proxy. 

I don't see the rotate option for FP-ACCESS-TOKEN-SECRET in my FHIR Proxy's key vault.

Here are some screenshots:- 

![image](https://user-images.githubusercontent.com/87669844/204806660-fa9042bb-bc03-4ead-bf45-0c885eec99d4.png)
![image](https://user-images.githubusercontent.com/87669844/204806769-8505605c-3999-47f2-864f-ec72fdf9d80f.png)
![image](https://user-images.githubusercontent.com/87669844/204806932-84244c57-d6b0-4fb5-8784-5535f2e5476d.png)

Any idea how can I rotate this secret? Inferno is asking to do the revocation prior to the execution of the test.

Thanks in advance!

**Comment by sordahl-ga** [comment]
You can use string to generate a random not easily guessed encryption string with sufficient length then use portal to access key vault and add a new version to the existing FP-ACCESS-TOKEN-SECRET secret.  Then recycle the proxy app.  Then any previous access tokens issued with the old encryption secret will fail....

**Comment by Kedar782** [comment]
@sordahl-ga 
This is my proxy function app.
![image](https://user-images.githubusercontent.com/87669844/204874458-595f21fd-565a-4bba-900c-48cf97c44ea1.png)
![image](https://user-images.githubusercontent.com/87669844/204874559-96c04ac5-58e6-4be8-bff8-56f2b217670f.png)
I don't see any key vault FP-ACCESS-TOKEN-SECRET version value here. So in my case, it only allows one version for the key vault FP-ACCESS-TOKEN-SECRET?
So should I delete the previous version and then make the new one?
Is this the right approach?

**Comment by Kedar782** [comment]
It worked. Thank you very much for this.

**Comment by vohuythao** [comment]
Thank you @sordahl-ga for your instruction
