### ISSUE TITLE
Questions about the visual inspection

### ISSUE THREAD

**Issue by Kedar782** [microsoft/fhir-proxy#86]
I followed the v2.0 branch documentation for the g(10) certification. I'm using MSI and AAD. 

I have received the proctor sheet from the Drummond group for the g(10) certification, in the proctor sheet they mentioned that for tests standalone patient API, limited access app, EHR APP, and single patient API after selection of the scopes user should enter user id and password.

If I use my Microsoft account userid/password for this then after the first test user gets cached in the browser and for the next tests it does not ask for userid/password. I'm not sure if we should Microsoft account userid and password for this or not
Here right now proxy only asks for userid. Please see the screenshot attached. Also, the first checkmark doesn't have any value. Why it is empty?
![image](https://user-images.githubusercontent.com/87669844/204876904-9ae0bcc1-d06a-4a81-a192-1dffb969c47b.png)

I also have questions about the visual inspection, they are expecting a demonstration about client registration for single and multiple patients. Any idea how can I create clients for single and multiple patients? Do I have to show them the client registration steps of standalone patient API and Multiple Patent API?

Also, the user should know about the offline_accesss scope. How can I achieve this?
I will really appreciate your help on this. My deadline is very near for the certification.

**Comment by sordahl-ga** [comment]
> I followed the v2.0 branch documentation for the g(10) certification. I'm using MSI and AAD.
> 
> I have received the proctor sheet from the Drummond group for the g(10) certification, in the proctor sheet they mentioned that for tests standalone patient API, limited access app, EHR APP, and single patient API after selection of the scopes user should enter user id and password.
> 
> If I use my Microsoft account userid/password for this then after the first test user gets cached in the browser and for the next tests it does not ask for userid/password. I'm not sure if we should Microsoft account userid and password for this or not Here right now proxy only asks for userid. Please see the screenshot attached. Also, the first checkmark doesn't have any value. Why it is empty? ![image](https://user-images.githubusercontent.com/87669844/204876904-9ae0bcc1-d06a-4a81-a192-1dffb969c47b.png)
> 
> I also have questions about the visual inspection, they are expecting a demonstration about client registration for single and multiple patients. Any idea how can I create clients for single and multiple patients? Do I have to show them the client registration steps of standalone patient API and Multiple Patent API?
> 
> Also, the user should know about the offline_accesss scope. How can I achieve this? I will really appreciate your help on this. My deadline is very near for the certification.

You can use the steps in the oncg10 document they show registration of a standalone and multiple patient API

The scope session restrictions are captured with user name, then password is entered and MFA is performed (if configured) then full scoping consent will be presented if it is the first time the user accesses the application which will include all scopes (offline_access, openid etc...) that must be consented to.

The first empty check box is simply allows you to select/deselect all scopes 

You can adjust the code to fit your needs this is simply a basic implementation and again is presented as is.
