### ISSUE TITLE
Single Patient API- Test Case-Server returns Provenance resources from Patient search by _id + revInclude:Provenance:target

### ISSUE THREAD

**Issue by preetinislur** [microsoft/fhir-proxy#88]
Hi Team,
 
We followed your ONC documentation we were able to execute most of the test cases.
 
But when we were running Single Patient API test, we figured out that there is a slash missing at the end of the base URL.
 
Please find the details in the attached document.
[Ticket_GitHub.docx](https://github.com/microsoft/fhir-proxy/files/10129245/Ticket_GitHub.docx)

Kindly please help for further steps.

**Comment by sordahl-ga** [comment]
What is the value of your FS-URL Application Setting on the fhir-proxy function app?

**Comment by preetinislur** [comment]
@sordahl-ga I Cloned latest build and this issue resolved.
