### ISSUE TITLE
How to perform 9.10.06 Health IT developer demonstrated the ability of the Health IT Module / authorization server to validate token it has issued.

### ISSUE THREAD

**Issue by Kedar782** [microsoft/fhir-proxy#89]
I followed the https://github.com/microsoft/fhir-proxy/blob/v2.0/docs/ConfigureProxyONCg10.md doc using v2.0.

How do I introspect access and refresh tokens for the test 9.10.06?

Also, For test 9.3, the Proctor sheet mentioned that the proctor will introspect the access token and refresh token. I'm using AAD. Any idea how can I introspect my access token? Is AAD provide any token introspection endpoint?

For test 9.10.04, they asked the user should deny/accept offline_access scope at the time of authorization. Or the user should be notified about the offline_access scope at the time of the authorization. Any idea how should I achieve it?

In my case, I can't able to see the offline_access scope during the active directory consent screen. I'm using offline_access in inferno before test execution or while creating an app as mentioned in the documentation.

Please see below screenshot attached:-
![image](https://user-images.githubusercontent.com/87669844/205186503-ae001803-7abc-46a2-8d83-2521ce06cf29.png)
![image](https://user-images.githubusercontent.com/87669844/205186925-a90c8a76-2022-47e1-84a8-c864e3c7d6dd.png)
![image](https://user-images.githubusercontent.com/87669844/205187417-c6f73c98-ab22-4e11-8558-a7c4b23f56f6.png)
Is anybody here, receiving the same thing for offline_access?
 
For test 2(Limited access), for the scope selection, UI's first scope is empty. The screen has no content for the first checkbox.

Anybody here received the same errors?
My certification is in next week. These things are very important for it. I will really appreciate your help on this.

**Comment by Kedar782** [comment]
@sordahl-ga 
Do you have any idea how can I introspect  access and refresh token?

**Comment by preetinislur** [comment]
Even Need help on the same step
