### ISSUE TITLE
Question: How can we setup the proxy with custom domain name?

### ISSUE THREAD

**Issue by vohuythao** [microsoft/fhir-proxy#92]
Hello,

Is there any guidance for setting up the FHIR proxy with custom domain name, such as https://emr.abc.com/fhir?

Thank you very much

**Comment by sordahl-ga** [comment]
You can select the custom domain option on the proxy function app or you can follow this guide (it uses Azure DNS) but you can use your DNS as well
https://learn.microsoft.com/en-us/azure/dns/dns-custom-domain

**Comment by Kedar782** [comment]
@vohuythao @sordahl-ga 

Where are you checking the version id and version name for the API?
We need to mention API version ID and version name in the documentation.

Is that why we need to use a custom domain for our API? 

Proctor said that we could get the version id using a database query. Proctor needs a screenshot for the version name and version id for the API.

Any idea where I can get the API version id and name?

Thanks in advanced!

**Comment by Kedar782** [comment]
@vohuythao 
Please ignore my above question. I resolved it.
How are you going to validate the access and refresh token for visual inspection 9.10.06?

**Comment by vohuythao** [comment]
> You can select the custom domain option on the proxy function app or you can follow this guide (it uses Azure DNS) but you can use your DNS as well https://learn.microsoft.com/en-us/azure/dns/dns-custom-domain

Thank you @sordahl-ga , but how about the App Registration for the proxy?

After I change the custom domain name for proxy function app, the Inferno G10 testing is failed.

I think because the name of App Registration is not correct anymore
Proxy function app : emr.abc.com
Proxy App Registration : sfp-proxyxxxxx.azurewebsites.net

This cause problem when authentication

Thank you

**Comment by Kedar782** [comment]
@vohuythao 
Are you passing Patient Context from your EHR for test 3 EHR App Launch?
Have you created the UI in your EHR for Scope selection?
It is mandatory for the certification.

**Comment by vohuythao** [comment]
Hello @Kedar782 

You mean for selection of scope offline_access , right?
The Proctor said that we can put this in EHR document, so that users can be informed by  reading the document
It's my understanding

Thank you

**Comment by Kedar782** [comment]
@vohuythao 
No, I mean Do you allow scope selection for FHIR resources from your EHR UI? Do you allow custom scope selection for the FHIR resources for 3rd test?
How do you launch EHR APP from EHR?
Do you select a patient first from your EHR and then pass this patient in the launch URL?
https://inferno.healthit.gov/suites/custom/smart/launch?iss={fhir-server-url}&launch=anystring
Here for launch =(anystring) we need to pass patient context(patient reference).

**Comment by vohuythao** [comment]
@Kedar782 

For Inferno test 3, I just run with FHIR endpoint, EHR clientid, clientsecret and then when this popup display
![image](https://user-images.githubusercontent.com/14121587/206624306-e9ea14cb-3902-4935-bf1a-a38963f5692e.png)

Just open this link in a new tab
https://inferno.healthit.gov/suites/custom/smart/launch?iss=https://sfp-proxyxxxx.azurewebsites.net/fhir&launch=test

**Comment by vohuythao** [comment]
When it ask for authentication with SMART server just login with my Azure AD account, and the scope selection is default

**Comment by Kedar782** [comment]
@vohuythao 
In the above link in a launch= test, we need to pass the patient context means the patient we selected from the EHR.

Are you done with your certification?

**Comment by Kedar782** [comment]
@vohuythao 

Which test is not passed?
Have you appeared for certification before?
My certification is on Monday.

**Comment by vohuythao** [comment]
@Kedar782 

We have not passed below test

![image](https://user-images.githubusercontent.com/14121587/206628237-1745e84e-9f57-4d09-baa8-33b25702e910.png)

**Comment by Kedar782** [comment]
How are you going to pass 9.10.04?
For me, the azure ad consent screen shows offline_access scope only once for the app(for standalone app launch and for EHR launch). This is what I'm planning to explain to my proctor.
For test 9.10.05, We need to attest that our token is valid for 3 months. I think verbal confirmation is valid for test 9.10.05. If not how are you going to pass 9.10.05?
For test 9.10.11 and test 9.10.12, I'm going to show Patient resource example in test 1.7 which element suffix and previous name. Is this valid for 9.10.11 and 9.10.12? If not how are you planning to pass these points?

**Comment by vohuythao** [comment]
@Kedar782 
9.10.4: we are planning to show the proctor that we have added offline_access scope in the EHR document, user will be informed by reading that document

9.10.5: I think we had solution here
https://github.com/microsoft/fhir-proxy/issues/93

9.10.11 and 9.10.12: We must add more elements for the Patient
https://build.fhir.org/ig/HL7/US-Core/Patient-example.json.html

![image](https://user-images.githubusercontent.com/14121587/206708863-50c410ea-8fce-4bc6-833b-86eb923756bc.png)

Hope these can help you in your certification

Thank you

**Comment by Kedar782** [comment]
@vohuythao 


Offline_Access Scope is seen in the Azure AD consent screen only for the first time when you use your app.

![image](https://user-images.githubusercontent.com/87669844/206752645-e17997ce-f764-4d99-92bb-fa321c1d9576.png)

But it only comes for the first time.

How did you demonstrate 9.10.10, 9.10.13 and 9.10.15?

**Comment by vohuythao** [comment]
Hello @Kedar782 

9.10.10: I don't remember exactly how we pass this, but I show the proctor this page
https://learn.microsoft.com/en-us/azure/active-directory/develop/id-tokens

9.10.13: This endpoint https://sfp-proxyxxxxx.azurewebsites.net/oauth2/token
Is the endpoint for issuing refresh token, backed by Azure AD

9.10.15: I think this will be auto pass if we already pass before tests

![image](https://user-images.githubusercontent.com/14121587/206760745-ca49fced-aefe-48cb-8218-f64d29991463.png)

**Comment by Kedar782** [comment]
![image](https://user-images.githubusercontent.com/87669844/206762095-06502f76-3f18-46eb-8cfe-7e57e0497fa1.png)
And when I hit the generate access token button I get the new access token and refresh token.
But I cannot able to store that refresh token in the postman. Are you using postman for the demonstration?

If yes, Can you please share the screenshot for the following in the postman?:-
1.  issuing refresh token in the postman and storing it in the postman
2.  refreshing the access token using the refresh token in the postman 

I really appreciate your help on this.

**Comment by vohuythao** [comment]
Hello @Kedar782 

So sorry that I have not used Postman to show this, just show the endpoint
https://sfp-proxyxxxxx.azurewebsites.net/oauth2/token

And this is ok with the Proctor

Good luck with your certification

**Comment by Kedar782** [comment]
@vohuythao 
I passed the certification. Thank you.
Any idea how can we use this API from our EMR and how are you planning to insert your real data into FHIR?
I have thousands of patients.
Thanks in advanced!

**Comment by vohuythao** [comment]
Hello @Kedar782 

Great to hear that, congrats to you!

About processing the data, I think you can recruit a data engineer with FHIR, HL7 experience.
This task is related to ETL, process data from SQL to the CosmosDB inside Azure API for FHIR

Thank you

**Comment by sordahl-ga** [comment]
Closing Issue as answered above for archival
