### ISSUE TITLE
Health IT Module attested that it is capable of issuing refresh tokens that are valid for a period of no shorter than three months

### ISSUE THREAD

**Issue by preetinislur** [microsoft/fhir-proxy#93]
Hi Team

For Visual Inspection for the step

Health IT Module attested that it is capable of issuing refresh tokens that are valid for a period of no shorter than three months
I checked the code it is 14 days for Refresh token Expiration, Is there a way to increase from azure portal.

**Comment by preetinislur** [comment]
@sordahl-ga kindly can u please suggest

**Comment by Kedar782** [comment]
@preetinislur 

Are you passing Patient Context from your EHR for test 3 EHR App Launch?
Have you created the UI in your EHR for Scope selection?
It is mandatory for the certification.

**Comment by preetinislur** [comment]
@Kedar782 yeah we are. We havent created any specific UI, just using Dynamic scope UI screen

**Comment by Kedar782** [comment]
@preetinislur 

Can you please explain your EHR launch in steps?
Have you created your own Dynamic Scope UI screen in your EHR?

I have created anything in my EHR for EHR App Launch. It only opens the redirect URL when I hit the launch button from my EHR.  The redirect URL does not have patient context. Also, I get the Azure AD Consent screen only for the first time. Will it be fine for the certification?

I really appreciate your help on this.

**Comment by preetinislur** [comment]
Hi Kedar,

We followed below steps
1. Created an EHR app using bash scripts.
2. Then we are launching EHR app from an Tab not through any our EHR application-- This is good for certification
3. Post authorization its returning back to inferno.
