### ISSUE TITLE
How to insert real data into FHIR server?

### ISSUE THREAD

**Issue by Kedar782** [microsoft/fhir-proxy#94]
I have all of my data stored in the SQL server. I have thousands of patients in the database. I cannot write POST Queries for those patients. Any idea how can I insert the data into SQL Server? I can generate the CCDA for every patient. Can I use this CCDA for data ingestion?

I will really appreciate your help on this.

**Comment by preetinislur** [comment]
Hi Kedar,

We need just 2 patients for certification.
option1: Manually enter the data
option2: Write a mapper from sql to fhir and migrate the data(we did this)

**Comment by Kedar782** [comment]
@preetinislur 

I'm not asking for the certification. I want to transfer all my data into Azure API for FHIR Database.
I have thousands of patients in the database. I cannot do the data ingestion process manually.
Can you please explain in detail how did you write the mapper?
I will really appreciate your help on this.
If you want we can discuss this 1:1. My email address is Kedarnaths782@gmail.com

**Comment by sordahl-ga** [comment]
Hey I'm going to close this issue as this is beyond the scope of this project.  There are several tooling options out there for ETL of data including data into FHIR.  Microsoft has several tools to assist in this the most purpose drive tool is  Azure Data Factory which can allow you to create transformative ETL pipelines.  We have had several customers use this to accomplish transform and load of proprietary schemas to FHIR....
https://azure.microsoft.com/en-us/products/data-factory/?OCID=AIDcmm5edswduu_SEM_b16729da64501a4d1b404a46df2ae27e:G:s&ef_id=b16729da64501a4d1b404a46df2ae27e:G:s&msclkid=b16729da64501a4d1b404a46df2ae27e
