### ISSUE TITLE
Creating the FHIR Proxy generates an error at the function app

### ISSUE THREAD

**Issue by jmarti326** [microsoft/fhir-proxy#95]
Storing Redis Connection String in KeyVault...
Creating Secure FHIR Proxy Function App [sfp-proxy5791]...
ERROR: Could not find a runtime version for runtime {} with functions version {} and os {}Run 'az functionapp list-runtimes' for more details on supported runtimes.

**Comment by jmarti326** [comment]
Anything will be helpful! Thank!

**Comment by MeijMarco** [comment]
Same problem here.

**Comment by kyle4health** [comment]
I am also running into this error.  Any throughts?

**Comment by sordahl-ga** [comment]
Deployment Issue Closing for repo archiving
