### ISSUE TITLE
Authentication Failed - When Calling FHIR Service Through Installed FHIR Proxy - Using v2.0 branch

### ISSUE THREAD

**Issue by conkman** [microsoft/fhir-proxy#96]
**Describe the Issue **
Currently I am working on a project to get G10 Certified.  We have installed the custom FHIR Proxy via the steps described on the docos on the v2.0 branch.  When I attempt to make a GET call to the FHIR Proxy which should then proxy the call to the FHIR Service I am consistenly getting a 401 Authentication Failed. 

GET https://sfp-proxy1758.azurewebsites.net/fhir/Patient/687cc08f-d2a1-2898-045c-87e8bc277c39
![image](https://user-images.githubusercontent.com/5832004/212150461-23fa1766-8ed5-4836-bb0a-b1b87ebaa946.png)

I am using the Inferno testing tool to make the call and to obtain the token.  Looking at the token I see the necessary scopes in my scope claim.  But the call fails.

**Steps to reproduce**
1.  Setup FHIR Service
2. Setup FHIR Proxy via docs.
3. Get token via authorization_code flow.
4. Call endpoint using proxy url GET https://sfp-proxy1758.azurewebsites.net/fhir/Patient/687cc08f-d2a1-2898-045c-87e8bc277c39
5. Get Response:  {
    "resourceType": "OperationOutcome",
    "id": "60678050f55c2faf3891cc8ac7b020ae",
    "issue": [
        {
            "severity": "error",
            "code": "login",
            "diagnostics": "Authentication failed."
        }
    ]
}

**Comment by conkman** [comment]
I am still running into this issue.  Also when I try to use the generated postman json and environments I get a Object Reference error when running the AuthorizedGetToken call.

![image](https://user-images.githubusercontent.com/5832004/213259997-e90476c0-c02a-44c3-ac41-0942113584bb.png)

**Comment by sordahl-ga** [comment]
This is due to configuration and will be closed to archive the repo.
